### ISSUE TITLE
Tag Images everything before that working fine

### ISSUE THREAD

**Issue by DaviJh** [Maximax67/LoRA-Dataset-Automaker#11]
![image](https://github.com/user-attachments/assets/a25962ef-ba5e-4f06-b7d1-112cf4810578)
![image](https://github.com/user-attachments/assets/1cb93a40-03f8-41de-a2fd-61fff2bd0b7a)
![image](https://github.com/user-attachments/assets/ff03997b-bde8-4086-9ff1-8dbb48db9499)

**Comment by Maximax67** [comment]
Fixed!
