### ISSUE TITLE
Find duplicates error

### ISSUE THREAD

**Issue by ryuji99** [Maximax67/LoRA-Dataset-Automaker#12]
![image](https://github.com/user-attachments/assets/d2c6ac36-31ca-4857-9222-a01b6bce1f90)

**Comment by nrocka** [comment]
I'm not a dev in any form, but using AI, I was able to get something to work. Try this on Cell 3 - 1
![image](https://github.com/user-attachments/assets/6d720a92-1f51-4584-ae07-9f264540dc41)


`# @title 1 Find duplicates
# @markdown This is how similar images should be for marking them to delete. I recommend 0.96 to 0.99 based on your needs:
similarity_threshold = 0.96  # @param {type:"number"}

# @markdown Batch sizes, if you don't know what it is, better don't touch:
embedding_batch_size = 200  # @param {type:"integer"}
similarity_matrix_batch_size = 1000  # @param {type:"integer"}

# @markdown Clip model name. You can choose another model from fiftyone zoo if you want. Just print its name here.
model_name = "clip-vit-base32-torch"  # @param {type:"string"}

dataset = fo.Dataset.from_dir(image_scrape_path, dataset_type=fo.types.ImageDirectory)


def make_embeddings(model_name, batch_size):
    model = foz.load_zoo_model(model_name)
    embeddings = dataset.compute_embeddings(model, batch_size=batch_size)

    # Convert embeddings to a NumPy array
    embeddings = np.array(embeddings)

    # Unload the model from the GPU to free up memory
    del model
    torch.cuda.empty_cache()

    return embeddings


def calculate_similarity_matrix(embeddings, similarity_threshold):
    # Directly calculate similarity over the entire embedding set
    similarity_matrix = cosine_similarity(embeddings)

    # Remove self-similarity by subtracting identity matrix
    similarity_matrix -= np.identity(len(similarity_matrix))

    # Apply the similarity threshold to filter out low-similarity pairs
    similarity_matrix[similarity_matrix < similarity_threshold] = 0

    return similarity_matrix


def make_samples(dataset, similarity_matrix, threshold=0.98):
    dataset.match(VF("max_similarity") > threshold)
    dataset.tags = ["delete", "has_duplicates"]
    id_map = [s.id for s in dataset.select_fields(["id"])]
    samples_to_remove = set()
    samples_to_keep = set()
    for idx, sample in enumerate(dataset):
        if sample.id not in samples_to_remove:
            # Keep the first instance of two duplicates
            samples_to_keep.add(sample.id)

            dup_idxs = np.where(similarity_matrix[idx] > threshold)[0]
            for dup in dup_idxs:
                # We kept the first instance so remove all other duplicates
                samples_to_remove.add(id_map[dup])
            if len(dup_idxs) > 0:
                sample.tags.append("has_duplicates")
                sample.save()
        else:
            sample.tags.append("delete")
            sample.save()

    return samples_to_remove, samples_to_keep


embeddings = make_embeddings(model_name, embedding_batch_size)

clear_output()
print("Embeddings calculated!")

# Use the similarity threshold when calculating the similarity matrix
similarity_matrix = calculate_similarity_matrix(embeddings, similarity_threshold)
print("Similarity matrix calculated!")

samples_to_remove, samples_to_keep = make_samples(dataset, similarity_matrix, similarity_threshold)
print(f"Remove percentage: {len(samples_to_remove) / (len(samples_to_remove) + len(samples_to_keep)) * 100}")

# Clean up
del embeddings, similarity_matrix, samples_to_remove, samples_to_keep
torch.cuda.empty_cache()

session = None
print("Done!")
`

**Comment by nrocka** [comment]
I'm not a dev at all, but using AI, i was able to get it to work for myself.
You can try to swap the Code on Cell 3 - 1 with this: [https://pastebin.com/raw/pJnC1D6q](https://pastebin.com/raw/pJnC1D6q)

**Comment by nrocka** [comment]
@Maximax67 You might wanna have a look at this. This error occurs when trying to decode corrupted images. It will not skip the images but instead throw this error. I made a cell that will detect and delete corrupt / invalid images.
I couldn't check the code for any issues or problems, as I'm not a dev at all and did this mostly with AI.

I pasted the cell over at pastebin, as I am unable to post the code in this comment with correct formatting (skill issue): https://pastebin.com/Edmx16vL

I'd be glad if you could implement this (or a similar fix) for this problem to your public notebook.

![image](https://github.com/user-attachments/assets/a5ee3b1c-94bd-41f5-8ea0-347a46022fe3)

**Comment by Maximax67** [comment]
Thank you. I am fixing this issue now. There is another bug with python dependencies. `compute_embeddings` method throws errors in console for all images. It looks like I need to roll back to an older version of one of the dependencies. I'm trying to fix that now.

The problem is in this line too:
```embeddings = dataset.compute_embeddings(model, batch_size=batch_size)```

**Comment by Maximax67** [comment]
I fixed all problems in the last commit
