### ISSUE TITLE
i cant save the image directly to google drive

### ISSUE THREAD

**Issue by yuchao532** [Maximax67/LoRA-Dataset-Automaker#2]
![1697149936259](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/57767005/4bbac45a-f198-4128-a6d3-deae6e249d06)
![1697150010359](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/57767005/8d534939-948e-4fd4-a4e2-0c71df49c41c)
no matter what acess i write,it can't  make the right way to my drive

**Comment by Maximax67** [comment]
I see, I know where the problem is. I will fix it today, thank you!

**Comment by Maximax67** [comment]
Fixed, thanks for mentioning the problem! If you find another bugs, feel free to open issues!

**Comment by yuchao532** [comment]
goood!
