### ISSUE TITLE
Infinite status error code 404 when downloading images from anime Zombie 100

### ISSUE THREAD

**Issue by DaviJh** [Maximax67/LoRA-Dataset-Automaker#3]
![image](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/75020215/65560e88-2d8d-45b8-94c7-401533495b87)

**Comment by Maximax67** [comment]
Hi, I checked and fixed this error. Image 25174254.jpg does not exist on fancaps.net, so the site responded with a 404 error, but in this case my code does not add +1 to the current retry count. So, the program ended up in an endless loop. Thank you very much for your report! I fixed that bug! Please try to download images again!

It also looks like there were a lot of read timeout errors in your output, you might want to try increasing the timeout.
