### ISSUE TITLE
Stop working on 3.1 -Find duplicates-

### ISSUE THREAD

**Issue by DaviJh** [Maximax67/LoRA-Dataset-Automaker#5]
![image](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/75020215/c8f4f1ae-0ee7-40b6-9c3d-fb364e8a5553)
Say something gets wrong on execution environment and that appear on logs

That error happened trying with " Total Drama " on fancaps i download season 1 and 3 and when i go to next part 3.1 that error happen do you have any ideia why?

it worked normal when i tried with only 1 episode and only one season

**Comment by Maximax67** [comment]
Sorry for the long wait. I couldn't find the problem. I checked the download of "Total Drama" on mine and everything downloaded correctly. I can't understand why it doesn't work for you. Judging by the error, your colab rebooted. The reason is not written here.
