### ISSUE TITLE
Error running Find Faces

### ISSUE THREAD

**Issue by ryuji99** [Maximax67/LoRA-Dataset-Automaker#7]
![image](https://github.com/Maximax67/LoRA-Dataset-Automaker/assets/167658678/bf7242ef-1512-4c3e-b14c-92fd2c48784f)

**Comment by Maximax67** [comment]
Hi. I've fixed the issue with saving cropped faces. Turns out it was caused by some updates in the YOLOv5 repo. I rolled back to the previous version using `git checkout`, and everything's back on track now.
Thanks for your patience!
