### ISSUE TITLE
1 Find duplicates Doesn;t work for ne

### ISSUE THREAD

**Issue by ShinobiiSpartan** [Maximax67/LoRA-Dataset-Automaker#9]
Whenever I use the Find duplicates cell, it always starts but then at the end, it gives me an error. I get this:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-28-19bd9982c81c>](https://localhost:8080/#) in <cell line: 80>()
     78 print("Embeddings calculated!")
     79 
---> 80 similarity_matrix = calculate_similarity_matrix(embeddings, similarity_matrix_batch_size)
     81 print("Similarity matrix calculated!")
     82 

[<ipython-input-28-19bd9982c81c>](https://localhost:8080/#) in calculate_similarity_matrix(embeddings, batch_size)
     25 
     26 def calculate_similarity_matrix(embeddings, batch_size):
---> 27     batch_size = min(embeddings.shape[0], batch_size)
     28     batch_embeddings = np.array_split(embeddings, batch_size)
     29     similarity_matrices = []

AttributeError: 'list' object has no attribute 'shape'

**Comment by nrocka** [comment]
Have a look at my comment, this worked for me.
[https://github.com/Maximax67/LoRA-Dataset-Automaker/issues/12#issuecomment-2386939707](https://github.com/Maximax67/LoRA-Dataset-Automaker/issues/12#issuecomment-2386939707)
